name: Terraform Deployment

on:
  push:
    branches:
      - terraform

  pull_request:
    branches:
      - terraform

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4